### ISSUE TITLE
Normalize email addresses

### ISSUE THREAD

**Issue by DanielHeath** [reinteractive/rails-salesforce-connect#1]
When searching for a contact it's important to downcase + strip the email address (on both sides?)

**Comment by lucascaton** [comment]
@DanielHeath according to my tests, Salesforce automatically normalizes it, so I think we don't have to worry about it:

![screen capture on 2018-06-21 at 16-39-45](https://user-images.githubusercontent.com/86755/41702034-fd8a2392-7571-11e8-896f-27146ba9d259.gif)
